package com.example.studyglows.navigation

sealed class Screen(val route: String) {
    object Welcome: Screen(route = "welcome")
    object Login: Screen(route = "login_screen")
    object Otp: Screen(route = "otp_screen")
    object Home: Screen(route = "home_screen")
    object Dashboard: Screen(route = "dashboard_screen")
    object Explore: Screen(route = "explore_screen")
    object Lecture: Screen(route = "lecture_screen")
    object AllCourses: Screen(route = "all_courses_screen")
    object CourseDetails: Screen(route = "course_details_screen")
    object FilterCourses: Screen(route = "filter_courses_screen")
    object SavedCourses: Screen(route = "saved_courses_screen")
    object Profile: Screen(route = "profile_screen")
    object Settings: Screen(route = "settings_screen")
    object Cart: Screen(route = "cart_screen")
    object EditorialsList: Screen(route = "editorial_list_screen")
    object EditorialDetails: Screen(route = "editorial_details_screen")
    object CurrentAffairsList: Screen(route = "current_affairs_list_screen")
    object CurrentAffairDetails: Screen(route = "current_affair_details_screen")
    object Vacancies: Screen(route = "vacancies_screen")
    object SavedVacancies: Screen(route = "saved_vacancies_screen")
    object TestSeriesScreen: Screen(route = "test_series_screen")
    object TestSeriesDashboard: Screen(route = "test_series_dashboard_screen")
    object ExploreTest: Screen(route = "explore_test_screen")
    object TestSeriesDetails: Screen(route = "test_series_details_screen")
    object TestsAttempted: Screen(route = "attempted_tests_screen")
    object SavedTests: Screen(route = "saved_tests_screen")
    object PopularTests: Screen(route = "popular_tests_screen")
    object TestScreen: Screen(route = "test_screen")
    object TestWelcome: Screen(route = "test_welcome_screen")
    object TestQuestions: Screen(route = "test_questions_screen")
    object TestResults: Screen(route = "test_results_screen")
}
